default_install_hook_types:
  - commit-msg
  - pre-push

repos:

# Хук для дампа версий
  - repo: local
    hooks:
      - entry: .hooks/pre-push-commitizen-bump
        id: pre-push-commitizen-bump
        language: script
        name: Commitizen Bump
        stages:
          - pre-push

# Хук проверки соответствия Conventional Commits от Commitizen
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg

